[phases.setup]
nixPkgs = ['nodejs_20', 'npm-9_x']

[phases.install]
cmds = ['npm install --include=dev']

[phases.build] 
cmds = ['echo "Building..." && npm run build && ls -la server/dist/ || echo "Server build failed"']

[start]
cmd = 'npm start'